### Python implementation of the Updating weight using the Back-Propagation and Gradient Descent Algorithm.

In [ ]:
import numpy as np

In [ ]:
input_value = np.array([[0,0],[0,1],[0,1],[1,1]])
input_value.shape
input_value


array([[0, 0],
       [0, 1],
       [0, 1],
       [1, 1]])

In [ ]:
output = np.array([0,1,1,0])
output = output.reshape (4,1)
output.shape

(4, 1)

In [ ]:
weights = np.array ([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [ ]:
bias =0.3

In [ ]:
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [ ]:
def der(x):
  return sigmoid_func(x)* (1-sigmoid_func(x))

In [ ]:
for ecochs in range (10000):
  input_arr = input_value
# back propagation
  weighted_sum = np.dot (input_arr , weights) + bias
  first_output = sigmoid_func(weighted_sum)

  error = first_output - output
  total_error = np.square (np.subtract (first_output,output)).mean()
# chain rule
  first_der = error
  second_der = der(first_output)
  derivative = first_der * second_der

  t_input = input_value.T
  final_derivative = np.dot (t_input ,derivative)
  # update Weight
  weights = weights -0.05*final_derivative
# update Bias
  for i in derivative:
      bias = bias - 0.05*i

In [ ]:
print(weights)
print (bias)

[[-7.94936582]
 [ 7.52086789]]
[-3.66639685]


In [ ]:
# prediction
pred = np.array ([1,1])

result = np.dot (pred, weights) + bias

res = sigmoid_func (result)

print(res)

[0.01638457]
